(source "gnu"   "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
(source "melpa" "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")

(depends-on "doom-themes")

(depends-on "evil")
(depends-on "evil-visualstar")
(depends-on "evil-leader")
(depends-on "evil-surround")
(depends-on "evil-nerd-commenter")
(depends-on "company")
(depends-on "dashboard")
(depends-on "async")
(depends-on "restart-emacs")
(depends-on "real-auto-save")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-swoop")
(depends-on "yasnippet")
(depends-on "yasnippet-snippets")
(depends-on "helm-describe-modes")
(depends-on "which-key")
(depends-on "iedit")
(depends-on "autopair")
(depends-on "org")
(depends-on "org-cliplink")
(depends-on "super-save")
(depends-on "moe-theme")
(depends-on "youdao-dictionary")
(depends-on "elpy")
(depends-on "py-yapf")
(depends-on "flycheck")
(depends-on "quickrun")
