(source "gnu"   "http://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")
(source "melpa" "http://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")

(depends-on "doom-themes")

(depends-on "evil")
(depends-on "evil-leader")
(depends-on "evil-surround")
(depends-on "evil-nerd-commenter")
(depends-on "company")
(depends-on "dashboard")
(depends-on "async")
(depends-on "restart-emacs")
(depends-on "helm")
(depends-on "which-key")
(depends-on "iedit")
(depends-on "autopair")
(depends-on "helm-ag")
(depends-on "helm-swoop")
(depends-on "helm-org-rifle")
(depends-on "org")
(depends-on "org-cliplink")
